apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fastapi-demo-build
spec:
  source:
    git:
      uri: https://github.com/hadrian89/fastapi-modal.git  # Replace with your GitHub repo URL
      ref: main  # Branch name
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.10'  # Base image used in the Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'fastapi-demo:latest'  # Tag where the built image will be pushed
  triggers:
    - type: GitHub
      github:
        secret: some-secret-token  # Optional: Use GitHub webhook secret for triggering builds
    - type: ConfigChange  # Trigger rebuilds when the BuildConfig changes
